# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v . && pwd && tree

    - name: Test
      run: go test -v ./...

    - name: TAG
      run: |
        echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        tree

    - name: Release and upload assets
      uses: softprops/action-gh-release@v0.1.6
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        files: |
          v2dat
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
